### ISSUE TITLE
cannot connect to ss after installed the Potatso app

### ISSUE THREAD

**Issue by deepsolo9** [haxpor/Potatso#13]
Hi, 

Thanks for your migration to Swift 3 of this project. :-) I followed the README.md file and successfully built and installed the Potatso app on my device. But the connection cannot be established. The scenario is that after I added the SS proxy and clicked the "Connect" button in the bottom, nothing happened just like I didn't click the button at all. The VPN config "Potatso" is created on the System Settings of iOS but there is no VPN icon showing connected on the top status bar. 

I didn't find any logs which may have any clues in the Xcode log window. Do you have any idea? Thanks.

**Comment by haxpor** [comment]
Thank you so much for reporting this issue @deepsolo9 .

I experienced the same on my other devices, and as per you said, there's no log of whatsoever.

Please give me the following information

* Xcode version that you successfully built
* iOS version
* iPhone model i.e. iphone 5s etc
* macOS version

I asked above info first because I can't narrow down the problem for now, so just in case.
PS. Not sure you're the same guy e-mailed me or not, if so you don't have to provide me above info again :)

I'll take a look thanks!

Thanks

**Comment by deepsolo9** [comment]
@haxpor Wow thanks for the quick reply. 

I built the project with Xcode 8.2.1, macOS Sierra 10.12.3 and ran the app on iPhone 6 with iOS 10.2.
Hope can help! 

ps: I am not the guy sent the email to you. :-)

**Comment by deepsolo9** [comment]
@haxpor This issue is fixed. 
The problem is related to the file sharing between the Host app and the extensions which means that the extension cannot read the config files generated by the host app. After I checked the APP Groups settings in the Capabilities and every other settings I can think of, it turns out to be a strange bug of Xcode 8.2. 

According to [this](http://stackoverflow.com/a/39876271), I just rebooted my MBP and it works!
Unbelievable!

**Comment by haxpor** [comment]
Hey thanks @deepsolo9 

Anyway, for others that still face the problem, there's a guy 简松亭 sent me e-mail told me he faced the same problem and and fix it by modifying sharedGroupIdentifier as seen below. May be this can help you too.

![screen shot 2017-03-08 at 1 59 30 pm](https://cloud.githubusercontent.com/assets/673757/23692140/dbe0d218-0407-11e7-85ed-00c8dd758fa2.png)

I will further investigate the root problem.

**Comment by Jasoncoool** [comment]
I am the guy sent the email to you. :-)

**Comment by haxpor** [comment]
Thank you guys. Fixed, and closed now.
