### ISSUE TITLE
clock_gettime(CLOCK_MONOTONIC, &ts) crashed 

### ISSUE THREAD

**Issue by happyfire** [haxpor/Potatso#14]
Hello, I checked out the project and try compile and run. The app runs successfully but can't connect to SS server. After debugging, I found the TunnelProvider network extension always crashes at clock_gettime(CLOCK_MONOTONIC, &ts), which is at BTime.h, in BTime_Init(). After use the alternative code path of using gettimeofday, SS server is successfully connected. I test in a iTouch of iOS 9.3.5. Do you think the gettimeofday code path is OK or is there a way to fix the crash of clock_gettime? Thanks!

**Comment by haxpor** [comment]
Thanks, didn't found this myself before too.

Could you describe the behavior that cannot connect? Is that similar to this normally run the app, click on connect button, the button flashes very fast but at the end cannot connect, goes like this...?

**Comment by happyfire** [comment]
The app can not connect to server without debugging too, so it is not a debug caused problem. The app behavior is just as you talked: " normally run the app, click on connect button, the button flashes very fast but at the end cannot connect, goes like this." 
So I run the app from xcode, and attach the process of PacketTunnel, and after press connect button of potatso, the code in PacketTunnelProvider is called, as you known, we enterd startTunnelWithOptions. Along the code path, I found when call clock_gettime(CLOCK_MONOTONIC, &ts), which is at BTime.h, in BTime_Init(), the process crashed.My XCode version is 8.2.1, the test device is a iPod Touch of iOS9.3.5. Please see this screenshot:
![742766d3-fa5c-44a5-be8e-fc84c77266ed](https://cloud.githubusercontent.com/assets/2919139/24032909/4838dd6a-0b25-11e7-91a6-6c8013d941cc.png)

**Comment by haxpor** [comment]
Thanks for confirming!

I researched and this might be the problem of Xcode 8 doesn't respect the min/max ios version to see if `clock_gettime` is available or not. More on this [here](https://github.com/gambit/gambit/issues/215). I believe the time when Potatso released on App Store, it's not the time for iOS 10 just yet. But now iOS 10 came, and thus a bug happens. It sets `HAVE_CLOCK_GETTIME` for all iOS version in build thus it crashes in runtime for iOS 9.

Not sure if this bug is fixed by Apple yet. The better way (in my opinion) is not to introduce new code path, but change via applying a preprocessor check wrapping around [this](https://github.com/icodesign/shadowsocks-libev/blob/master/config.h#L29) as if it's iPhone then `#undef HAVE_CLOCK_GETTIME`.

Also `shadoowsocks-libev` is the core dependency which should not be quickly modify, the fix we will do might change the dependency location to forked one first, then see if we can send a patch to them for merge, then we could go back to original one.

I try to do this over the course of weekend and onwards.
For now, I believe you and other users that affected might try to manually edit `config.h` file of `shadowsock-libev` at line 29 (same as above) but do it **locally** to change it to be as follows

```c
/* Define to 1 if you have the `clock_gettime' function. */
#if TARGET_OS_IPHONE == 1
#undef HAVE_CLOCK_GETTIME
#endif
```
Due to when we set above, these [lines](https://github.com/icodesign/shadowsocks-libev/blob/master/libev/ev.c#L68-L82) will help determine which function to use automatically :)

**Comment by happyfire** [comment]
Yes, I checked the time.h of xcode 8.2, there is:
```
#define __CLOCK_AVAILABILITY __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0) __TVOS_AVAILABLE(10.0) __WATCHOS_AVAILABLE(3.0)
__CLOCK_AVAILABILITY
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
```
So clock_gettime is only avaliable since ios10.
Actually, tun2socks provides itself version of clock_gettime in BTime.c, but if we uncomment it there will be a compile error because it confilicts with system version declaration. So I take a work around of rename the clock_gettime in BTime.c to clock_gettime_ex, and luckily, there is only two call in BTime.h so it's easy to change the call code and finally it works.

And for #undef HAVE_CLOCK_GETTIME in config.h in shadowsocks_libev, I have not test that, it looks not relative to code in BTime.

**Comment by haxpor** [comment]
Thanks for effort. I need to take a look at it more then.
Noted on your finding.

**Comment by haxpor** [comment]
Ohh you're right, I got it now. During migration to swift 3, I have commented that code both in `BTime.c` and `BTime.h` as it's conflict (as you said) in iOS 10.

You point out in the right direction! 👍
I applied a cleaner way to fix this by checking if you have iOS 10 SDK then you should not define such function again as it'd be conflict, otherwise use it. I will test on real device to confirm later tonight.

Snippet of what would be changed in fixed version

In `BTime.h`
```c
#ifdef __MACH__
    #define CLOCK_MONOTONIC 1
    #ifndef __IPHONE_10_0
    int clock_gettime(int clk_id, struct timespec* t);
    #endif
#endif
```

In `Btime.c`
```c
#ifdef __MACH__
#include <mach/clock.h>
#include <mach/mach.h>

#ifndef __IPHONE_10_0
int clock_gettime(int clk_id, struct timespec* t)
{
    clock_serv_t cclock;
    mach_timespec_t mts;
    host_get_clock_service(mach_host_self(), CALENDAR_CLOCK, &cclock);
    clock_get_time(cclock, &mts);
    mach_port_deallocate(mach_task_self(), cclock);
    t->tv_sec = mts.tv_sec;
    t->tv_nsec = mts.tv_nsec;
    return 0;
}
#endif
#endif
```

**Comment by haxpor** [comment]
@happyfire Thank you for pointing into the right direction. I agree and think that it's not worth to overthinking about this issue. Making a change like you did is better way to go.

Do you want to send in PR? I'm happy to merge in.

**Comment by happyfire** [comment]
Thanks, currently we are researching potatso for a internal project, so has not forked potatso.

**Comment by haxpor** [comment]
That's fine. I can do it.

**Comment by aishuidedabai** [comment]
#define __CLOCK_AVAILABILITY __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0) __TVOS_AVAILABLE(10.0) __WATCHOS_AVAILABLE(3.0)
__CLOCK_AVAILABILITY
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);  这段代码请问在哪查看的，时间确实有问题，我还原了错误 @happyfire

**Comment by AirChen** [comment]
clock_gettime 的定义time.h里面

**Comment by AirChen** [comment]
@aishuidedabai clock_gettime的定义time.h里面

**Comment by aishuidedabai** [comment]
多谢
