### ISSUE TITLE
The request of 'https://api.potatso.com/rulesets' returns 404.

### ISSUE THREAD

**Issue by willbin** [haxpor/Potatso#20]
`
{ URL: https://api.potatso.com/rulesets/detail } { status code: 404, headers {
    "Content-Length" = 9;
    "Content-Type" = "text/plain; charset=utf-8";
    Date = "Wed, 05 Apr 2017 07:02:54 GMT";
    Server = "nginx/1.11.10";
    "x-response-time" = 0ms;
} })
fatal error: unexpectedly found nil while unwrapping an Optional value
`

And this leads an fatal error.

What's happening?

**Comment by haxpor** [comment]
Did you crash on this [line](https://github.com/haxpor/Potatso/blob/c60888f61aae5f14a561652dd5c774cc47f72e1a/Potatso/Core/API.swift#L255)?

If so this has been fixed in this [commit](https://github.com/haxpor/Potatso/commit/d74e7114b09960034795c595052e5041aca956b8). Please pull the latest code again.

It due to swift 3 migration as seen on _Code Notices_ as there's no good solution yet stated in README.md.

**Comment by happyfire** [comment]
It seems api.potatso.com has some problem. This problem occurs serval days before, the api.potatso.com return "404".

**Comment by willbin** [comment]
@haxpor Anything new about this 404 issue?

**Comment by so898** [comment]
@willbin This URL is the API URL of the Potatso for rule market service.
Since @icodesign no long sells the Potatso in App Store, and there is a new version Potatso 2, I think he redesign the API of this part.
The new API is provided to Potatso 2 not Potatso, and the old one is deleted. Without the API code and SQL design of old API, I don't think this issue could be fixed later.

However, without rule market service, the main function and services of Potatso are still OK.

Maybe we should remove the related code in the project? @haxpor

**Comment by willbin** [comment]
@so898 
I guess so and I agree with that removing 'Rule Market' related codes.
On the other side, we should add some useful rules into this project by default to use.

**Comment by haxpor** [comment]
Thank you guys for suggestion and great technical conversation! Apologize I didn't have time to pay much attention to Potatso since stable port to Swift 3.

Yes, your observation is right about API. We should remove or replace those code with something relevant (our own) or useful rules. Migrating these areas are always on my mind to be honest. All in all, PR is very welcome :)

**Comment by haxpor** [comment]
Closed, and move over to #62 .
