### ISSUE TITLE
Hope to support gcm encryption method

### ISSUE THREAD

**Issue by xsren** [haxpor/Potatso#36]
For example: "aes-128-gcm".

Thanks!

**Comment by haxpor** [comment]
I think this has to do with updating shadowsocks-libv, you can refer to [this](https://github.com/haxpor/Potatso/issues/22#issuecomment-306403067) and [this](https://github.com/haxpor/Potatso/issues/22#issuecomment-306522935) as @so898 already pushed effort on it and discovered something interesting. I didn't look into it myself yet due to time factor. You might want to subscribe to that thread in case any update comes up.

PS. I saw that you already noticed that thread too.

**Comment by xsren** [comment]
OK! Thanks for your great job!
