### ISSUE TITLE
我的无法编译运行呢。

### ISSUE THREAD

**Issue by godwar10** [haxpor/Potatso#37]
pod install 后
Fetching podspec for `Aspects` from `./Library/Aspects/`
Fetching podspec for `CallbackURLKit` from `./Library/CallbackURLKit`
[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`
求指点啊。

**Comment by haxpor** [comment]
I suspect you didn't execute `git submodule update --init` as seen [here](https://github.com/haxpor/Potatso#how-to-build-project).

**Comment by godwar10** [comment]
@haxpor  3q，I did that。I'm trying it again

**Comment by godwar10** [comment]
yansideyudeimac:Potatso-master zhengmingxiang$ git submodule update --init
yansideyudeimac:Potatso-master zhengmingxiang$ git submodule update --init
yansideyudeimac:Potatso-master zhengmingxiang$ pod install
Analyzing dependencies
Fetching podspec for `Aspects` from `./Library/Aspects/`
Fetching podspec for `CallbackURLKit` from `./Library/CallbackURLKit`
[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`
yansideyudeimac:Potatso-master zhengmingxiang$ 


I'm trying it again but all the same

**Comment by haxpor** [comment]
Ok. Could you please check that there are files existing in `CallbackURLKit`?
If it's not, this means `git submodule update --init` has error and doesn't complete the operation.

Due to nature of `git submodule`'s updating mechanism, it can fail silently. If it didn't work, remove the cloned repository, then clone and start over again.

Let me know if you still face the problem.

**Comment by godwar10** [comment]
I remove the cloned repository, then clone and start over again. right now

**Comment by godwar10** [comment]
i do it ,but permission denied (publickey).


git submodule update --init
Submodule 'Library/CallbackURLKit' (git@github.com:phimage/CallbackURLKit.git) registered for path 'Library/CallbackURLKit'
Submodule 'Library/Eureka' (git@github.com:haxpor/Eureka.git) registered for path 'Library/Eureka'
Submodule 'Library/ShadowPath/ShadowPath/libmaxminddb' (git@github.com:haxpor/libmaxminddb.git) registered for path 'Library/ShadowPath/ShadowPath/libmaxminddb'
Submodule 'Library/ShadowPath/ShadowPath/shadowsocks-libev' (git@github.com:icodesign/shadowsocks-libev.git) registered for path 'Library/ShadowPath/ShadowPath/shadowsocks-libev'
Cloning into '/Users/zhengmingxiang/Desktop/Potatso/Library/CallbackURLKit'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:phimage/CallbackURLKit.git' into submodule path '/Users/zhengmingxiang/Desktop/Potatso/Library/CallbackURLKit' failed
Failed to clone 'Library/CallbackURLKit'. Retry scheduled
Cloning into '/Users/zhengmingxiang/Desktop/Potatso/Library/Eureka'...
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by godwar10** [comment]
when I implement it ,The folder of CallbackURLKit cannot be found

**Comment by haxpor** [comment]
Ok, thanks for testing this out. The problem is due to url used to fetch remote repository is via `ssh` i.e. `git@github.com:/phimage/CallbackURLKit.git` and that requires anyone who clones the repository to set up SSH Keys. Please set it up [here](https://github.com/settings/keys). In that link, you will see a how-to link on how to do it.

Then later after successfully set up SSH Key, please remove the repository folder, then close and start it over again.

**PS**: I will update the project to depend on `https` when pull remote repository instead to get rid of problem you found by others in future.

**Comment by godwar10** [comment]
This is my new computer, so I forgot to add it。 I have try

**Comment by godwar10** [comment]
thank you very much

[!] Error installing Crashlytics
[!] /usr/local/bin/curl -f -L -o /var/folders/qn/7p9692_j6sd0hvlmhk2804zh0000gn/T/d20170803-30666-1sk2wd/file.zip https://kit-downloads.fabric.io/cocoapods/crashlytics/3.7.3/crashlytics.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  8 9011k    8  735k    0     0   1812      0  1:24:52  0:06:55  1:17:57     0
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

I'll see what to do with it

**Comment by haxpor** [comment]
Alright! Seems to be problem with cocoapod now. Feel free to reopen this issue if you still experience problem. Thanks.
