### ISSUE TITLE
error:invalid redeclaration of '~' In Cartography

### ISSUE THREAD

**Issue by holyen** [haxpor/Potatso#53]
the Cartography version: 3.0.1
but error
how to fix it

**Comment by JeansHuang** [comment]
JeansHuang/Potatso  Work for Xcode9.1 iOS11.1 Swift3.2

**Comment by haxpor** [comment]
@holyen This might result from executing `pod update` in which it will pull in newer version of dependency. As of Potatso uses `Cartography (1.0.1)` not `3.0.1`.

Please make sure **not to execute** `pod update`. The project relies on fixed version as can be seen in `Podfile.lock`. What you can do to resolve this issue is to start fresh, remove everything, then start it all over.

Feel free to re-open this issue if you still face the problem. I'm happy to help.
