### ISSUE TITLE
[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`

### ISSUE THREAD

**Issue by ruchiragile** [haxpor/Potatso#9]
I am trying to install the pods but following podspec is not found:

[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`

Please provide the proper path

**Comment by haxpor** [comment]
Hey @ruchiragile , are you sure you fetch the latest code from this repository?
And did you execute the first step to update git submodules? Then you can check if it get fetched properly by looking at `./Library/CallbackURLKit` directory from the root project directory.

**Comment by ruchiragile** [comment]
yes, I did the same as suggested in read me file.

$ cd /Users/mymac/Documents/Projects/PotatsoTest/7FEB/Potatso-master 
$ git submodule update --init
$ pod install
Analyzing dependencies
Fetching podspec for `Aspects` from `./Library/Aspects/`
Fetching podspec for `CallbackURLKit` from `./Library/CallbackURLKit`
[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`

**Comment by haxpor** [comment]
It seems like git submodule didn't fetch source files from remote `CallbackURLKit` repo.
Could you please check for me whether there is folder `./Library/CallbackURLKit` and inside the folder there are also source files **after** you do `git submodule update --init`.

**Comment by ruchiragile** [comment]
yes I have checked, there are no files inside the folder ./Library/CallbackURLKit as well in another folder named ./Library/Eureka just for your reference.

**Comment by haxpor** [comment]
Ok @ruchiragile , I strongly believe git update submodule failed silently due to [this](https://github.com/haxpor/Potatso/blob/master/.gitmodules#L6) was removed (related #6), and `Eureka` and `CallbackURLKit` are defined right after that one so they might not get updated.

Please be patient until #6 get fixed. This should solve your issue too.

**Comment by ruchiragile** [comment]
@haxpor Ok, looking forward to see updates from you soon 👍 and thanks for the quick replies :)

**Comment by haxpor** [comment]
@ruchiragile #6 is fixed on 4086e2e. Just make sure you pull the latest code and try again. It should work now 👌

**Comment by ruchiragile** [comment]
Hi @haxpor 

Downloaded the latest code, though unable to update the submodules, see the below response:

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:phimage/CallbackURLKit.git' into submodule path '/Users/MyMac/Desktop/POTATSO 10/Potatso/Library/CallbackURLKit' failed

**Comment by haxpor** [comment]
@ruchiragile Your problem seems to be different issue. It looks like you clone down to different computer you used before? Thus SSH-Key is not recognized by Github server, so it didn't allow you to access the repository. Make sure you follow these steps https://help.github.com/articles/connecting-to-github-with-ssh/.

And make sure to pull down the latest code again.
